services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        user: sail
        ports:
            - '80:80'
        volumes:
            - './:/var/www/html'
        depends_on:
            - mysql
            - redis
        networks:
            - sail
        extra_hosts:
            - 'host.docker.internal:host-gateway'
    mysql:
        image: 'mysql:5.7'
        ports:
            - '3306:3306'
        environment:
            MYSQL_ROOT_PASSWORD: rootpassword
            MYSQL_DATABASE: laravel
            MYSQL_USER: sail
            MYSQL_PASSWORD: 123
        volumes:
            - 'mysql:/var/lib/mysql'
        networks:
            - sail
    redis:
        image: 'redis:alpine'
        ports:
            - '6379:6379'
        networks:
            - sail
networks:
    sail:
        driver: bridge
volumes:
    mysql: null
